set-option -g default-command fish

# Prefix
set -g prefix 'C-a'
unbind-key C-b
unbind-key C-a

# Open new panes/windows in current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# vi-like keys
set-window-option -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Mouse
set -g mouse on
unbind -T copy-mode MouseDragEnd1Pane
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Status bar
set-option -g status-position top
set -g status-justify left
set -g status-style 'fg=red'
set -g status-left ''
set -g status-left-length 10

setw -g window-status-current-style 'fg=black bg=yellow'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=red bg=default'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '
setw -g window-status-bell-style 'fg=yellow bg=red bold'

set -g pane-active-border-style fg=white
set -g pane-border-lines heavy
