# Generated by nixos-generate-config — edit with care
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6718514c-0398-4f6d-b69c-c0cfd7c4b194";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-efbff727-309e-4514-b8c8-52858020c527".device =
    "/dev/disk/by-uuid/efbff727-309e-4514-b8c8-52858020c527";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F1BB-5A90";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
